import React from 'react';
import { Printer, Download, ArrowLeft, FileCheck, Activity, HeartPulse } from 'lucide-react';
import { AnalysisResult } from '../types';
import { Button } from './Button';
import { DISCLAIMER_TEXT } from '../constants';

interface ResultsDisplayProps {
  result: AnalysisResult;
  onReset: () => void;
}

export const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, onReset }) => {
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="w-full max-w-4xl mx-auto pb-12">
      {/* Toolbar - Hidden when printing */}
      <div className="flex flex-col sm:flex-row justify-between items-center mb-8 no-print gap-4">
        <Button variant="ghost" onClick={onReset} className="self-start sm:self-auto">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Analyze Another Report
        </Button>
        
        <div className="flex gap-3">
          <Button onClick={handlePrint} variant="primary">
            <Printer className="mr-2 h-4 w-4" />
            Print / Save as PDF
          </Button>
        </div>
      </div>

      {/* Main Printable Content */}
      <div className="bg-white shadow-lg rounded-2xl overflow-hidden border border-slate-100 print:shadow-none print:border-none print:rounded-none">
        
        {/* Header of Report */}
        <div className="bg-teal-600 p-8 text-white print:bg-white print:text-black print:border-b-2 print:border-black print:p-0 print:mb-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold mb-2">Translated Medical Report</h1>
                    <p className="opacity-90 print:text-slate-600">Original File: {result.originalFileName}</p>
                </div>
                <div className="text-right hidden print:block">
                    <p className="text-sm text-slate-500">Generated by MediTranslate AI</p>
                    <p className="text-sm text-slate-500">{new Date().toLocaleDateString()}</p>
                </div>
            </div>
            <div className="mt-4 inline-block px-3 py-1 bg-white/20 rounded-full text-sm font-medium print:hidden">
                Target Language: {result.targetLanguage}
            </div>
        </div>

        <div className="p-8 print:p-0">
            
            {/* Disclaimer for Print */}
            <div className="mb-8 p-4 bg-amber-50 border-l-4 border-amber-500 text-amber-800 text-sm rounded print:border print:border-amber-500">
                <p className="font-bold mb-1">⚠️ Important Disclaimer</p>
                {DISCLAIMER_TEXT}
            </div>

            <div className="grid gap-8">
                
                {/* Summary Section */}
                <section className="border rounded-xl p-6 bg-slate-50 print:bg-transparent print:border print:border-slate-300">
                    <div className="flex items-center gap-3 mb-4 text-teal-700 print:text-black">
                        <FileCheck className="h-6 w-6" />
                        <h2 className="text-xl font-bold">Report Summary</h2>
                    </div>
                    <div className="prose prose-slate max-w-none text-slate-800 leading-relaxed whitespace-pre-line">
                        {result.summary}
                    </div>
                </section>

                {/* Medical Advice Section */}
                <section className="border rounded-xl p-6 bg-blue-50 border-blue-100 print:bg-transparent print:border print:border-slate-300">
                    <div className="flex items-center gap-3 mb-4 text-blue-700 print:text-black">
                        <HeartPulse className="h-6 w-6" />
                        <h2 className="text-xl font-bold">Medical & Lifestyle Advice</h2>
                    </div>
                    <div className="prose prose-blue max-w-none text-slate-800 leading-relaxed whitespace-pre-line">
                        {result.medicalAdvice}
                    </div>
                </section>

                {/* Full Translation Section */}
                <section className="mt-4">
                    <div className="flex items-center gap-3 mb-6 pb-2 border-b border-slate-200">
                        <Activity className="h-6 w-6 text-slate-400 print:text-black" />
                        <h2 className="text-2xl font-bold text-slate-900">Full Translated Report</h2>
                    </div>
                    <div className="prose prose-lg max-w-none text-slate-800 bg-white rounded-lg whitespace-pre-wrap font-serif">
                        {result.translatedText}
                    </div>
                </section>

            </div>
        </div>

        {/* Footer for Print */}
        <div className="bg-slate-50 p-6 border-t border-slate-100 text-center text-slate-500 text-sm print:mt-8 print:border-t print:pt-4">
            <p>MediTranslate AI - Empowering health through language.</p>
        </div>
      </div>
    </div>
  );
};